{{- if .Values.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" $ }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "fullname" $ }}
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
    app.kubernetes.io/managed-by: "{{ $.Release.Service }}"
data:
  config.json: |
  {{ toYaml .Values.config | nindent 4 }}
{{- end }}
