{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "fullname" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "fullname" $ }}
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
    app.kubernetes.io/managed-by: "{{ $.Release.Service }}"
spec:
  endpoints:
  - path: /metrics
    port: http
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "fullname" $ }}
      app.kubernetes.io/instance: "{{ $.Release.Name }}"
      app.kubernetes.io/managed-by: "{{ $.Release.Service }}"
{{- end }}